### ISSUE TITLE
Map is not shown

### ISSUE THREAD

**Issue by alexd555** [mitchtabian/Google-Maps-2018#4]
Hi,

Map is not shown.
I don't see place where I can enter API Key

Thanks,
Alex

**Comment by mitchtabian** [comment]
Hello Alex.
Did you watch this video?
https://codingwithmitch.com/courses/android-google-maps-directions-api/integrating-google-maps-sdk/

**Comment by alexd555** [comment]
It's Ok.
Thanks.
