### ISSUE TITLE
WindowManager is not recognized

### ISSUE THREAD

**Issue by alexd555** [mitchtabian/Google-Maps-2018#5]
WindowManager is not recognized

**Comment by mitchtabian** [comment]
Please provide more information.

- errors?
- logs?
- What were you trying to do?
- What video were you watching?

**Comment by alexd555** [comment]
![image](https://user-images.githubusercontent.com/25776246/51379143-69848100-1b17-11e9-904d-fa1f31c07b7f.png)

**Comment by mitchtabian** [comment]
It's red. If it's red you probably didn't import the library. What code are you referencing?

**Comment by alexd555** [comment]
I didn't manage to find which library I need to import.

**Comment by mitchtabian** [comment]
Android Studio tells you what you need to import. Press ALT+ENTER and it will do it automatically.
This is the one you're missing: 
`import android.view.WindowManager;`

**Comment by alexd555** [comment]
The App crash if I use this function after import this library
