### ISSUE TITLE
The code is a bit different from video

### ISSUE THREAD

**Issue by alexd555** [mitchtabian/Google-Maps-2018#6]
Hi,

Where can I find the same code as in video ? 
I choose a suitable branch but it is a bit different and lacks code snippets.
For example,
google_map_api.xml doesn't exist.
There are additional codes that you added online.

I also saw that you copied code and configuration from other GitHub link.

Thanks,
Alex

**Comment by alexd555** [comment]
Maybe, It's Ok. I'm checking

**Comment by mitchtabian** [comment]
The code is not different.
All links to the correct source code are in the description of the videos.
And I didn't copy paste anything into the video you mentioned.
There is no file named "google_map_api.xml" in any of the branches or videos.
