### ISSUE TITLE
Filtering online users by radius in map and chatroom.

### ISSUE THREAD

**Issue by alexd555** [mitchtabian/Google-Maps-2018#7]
Hi,

I want to add to this application the following feature:
Filtering online users by radius in map and chatroom.

Could you tell me what relevant information will help me to do it ? I don't see that you do it on your code.

Thanks,
Alex

**Comment by mitchtabian** [comment]
Alex,

Please don't create issues for things like this. This is a **question**. Not an issue.

If you have questions you can post comments on YouTube or become a [member](https://codingwithmitch.com/enroll/) on my website and ask in the discord channel.

Using a distance algorithm to filter users is outside the scope of this course. But if I was going to implement something like that I would use the latitude and longitude coordinates to make a triangle and use the hypotenuse.
