### ISSUE TITLE
FirebaseAuth.getInstance().getUid() - How does it work?

### ISSUE THREAD

**Issue by alexd555** [mitchtabian/Google-Maps-2018#9]
I have 3 questions about this:
FirebaseAuth.getInstance().getUid()

1. According to spec, getInstance() returns instance of the FirebaseAuth class, but the getUid not function in this class. But it works. How ?

2. It seems that getUid generates unique ID if this is a new user but it is not written in the spec. How does this function work?

3. When does it throw exception or return null ?

Thanks,
Alex

**Comment by mitchtabian** [comment]
Alex,

Once again, that is not an issue. This is not a place to ask questions like that. Leave questions in YouTube comments or in the comments section on my website.

As for your question, read the docs:
https://firebase.google.com/docs/auth/?&gclid=EAIaIQobChMItfqnu8Od4AIVFr3sCh185geEEAAYASAAEgI0BPD_BwE
